export const INSERT_NEW_USER = 'INSERT_NEW_USER';
export const CHANGE_STAGE = 'CHANGE_STAGE';
export const UPDATE_VERSION_NUMBER = 'UPDATE_VERSION_NUMBER';
export const FINISH_EXPLAINATION = 'FINISH_EXPLAINATION';
