export const INSERT_NEW_USER = 'INSERT_NEW_USER';
export const CHANGE_STAGE = 'CHANGE_STAGE';
export const UPDATE_VERSION_NUMBER = 'UPDATE_VERSION_NUMBER';
export const FINISH_EXPLAINATION = 'FINISH_EXPLAINATION';
export const GET_USER_IP = 'GET_USER_IP';

export const INCREASE_CHART_LABEL = 'INCREASE_CHART_LABEL';
export const INSERT_CYCLE_TO_HISTORY = 'INSERT_NEW_MARKET_DATA';
export const INSERT_NEW_CHART_DATA = 'INSERT_NEW_CHART_DATA';
export const INSERT_NEW_CHART_MARKET_DATA = 'INSERT_NEW_CHART_MARKET_DATA';
export const INSERT_NEW_CYCLE_TO_DB = "INSERT_NEW_CYCLE_TO_DB"
